### ISSUE TITLE
插件在koishi中无法正常使用

### ISSUE THREAD

**Issue by DaiMao204** [koishijs/koishi-plugin-mediawiki#14]
如题
![ce2d23507dc525b32b99ed342508a6b2](https://github.com/user-attachments/assets/560e06a1-fe56-4d5f-93d6-f362ace3d193)

**Comment by RushCN** [comment]
你去日志里面看看，应该会有文本类型相关的报错信息，跟着那个报错信息找到那个文件更改就可以了。

**Comment by dragon-fish** [comment]
理论上更新到 3.x 可以解决此问题

**Comment by dragon-fish** [comment]
@DaiMao204 any updates?
