### ISSUE TITLE
大哥，求教这个控制台跑不通，docker装的koishi

### ISSUE THREAD

**Issue by 1787755656** [koishijs/koishi-plugin-mediawiki#15]
![log](https://github.com/user-attachments/assets/7052eaf4-dd4b-4df7-a693-5dc894edba39)
不知道那些安装方法应该怎么用，有没有更具体的一个，比如某个wiki例子

**Comment by 1787755656** [comment]
![22](https://github.com/user-attachments/assets/ec539058-b42b-45a2-b5de-fedf78d9188b)
z装上老版本可以打开管理页面了，但是报错饥荒wiki

**Comment by itzdrli** [comment]
![Image_1728090248768.png](https://github.com/user-attachments/assets/7b3e531e-b289-4d8b-a444-ff5a40aadb3f)

**Comment by 1787755656** [comment]
这个官方wiki可以用但是我应该在个文件调整可以扩大获取的信息，现在获取 的信息只有一小块

**Comment by 1787755656** [comment]
我又调整调整了一下，但是里面有一些不想要的元素，但是他们都包在一个div里面我不知道应该怎么写规则去掉
![QQ20241104-180521](https://github.com/user-attachments/assets/acd18433-bb66-4952-afb3-d2fead90dcd1)
![image](https://github.com/user-attachments/assets/8597f75c-0f92-4948-bec9-1727c664ccf5)

**Comment by 1787755656** [comment]
我现在就是想屏蔽一些无关的元素（类似于萌娘百科的导航栏截图会盖住上半部分文字，还有公告栏），最好是让他都不加载，因为不知道为啥，有些配方的图片都还没加载出来，返回的图，但是这个广告和广告视频都出来了，
